#!/usr/bin/env python
# Engine module build

Import("env")

module_env = env.Clone()
module_env.Append(CPPPATH=[Dir("src").srcnode().abspath])

module_env.add_source_files(env.modules_sources, "*.cpp")
module_env.add_source_files(env.modules_sources, "src/*.cpp")
